// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cblwogjlcidzjhkxvowy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNibHdvZ2psY2lkempoa3h2b3d5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MTI5NTUsImV4cCI6MjA3MDQ4ODk1NX0.kNPDV6gI6_ViIOS0mJEWRV2OFo-nUoB_ICjprxJEOI4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});